config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  resources :projects, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many_attached :photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @project = Project.last
  end

  def about
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all.order(start_date: :desc)
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/KPenzes"><i class="fa-brands fa-github" title="Github"></i></a>
    <a href="https://www.linkedin.com/in/kirstin-penzes/"><i class="fab fa-linkedin" title="LinkedIn"></i></a>
  </div>
  <div class="footer-copyright">
    <p>
      <strong>Looking to get your project started?</strong>
      <br>
      Contact me on<strong>
      <a href="https://www.linkedin.com/in/kirstin-penzes/" target="_blank" style="color:#87CABA" >LinkedIn</a></strong>.
    </p>
  </div>
</div>

app/views/layouts/_home_banner.html.erb
<div class="home-banner" style="background-image: url('https://i.ibb.co/KhznPWc/yellow-cubes-2.png')">
  <h1>Hi, I'm Kirstin!</h1>
  <h5>A web developer from Montreal.</h5>
  <%= link_to "Contact me", about_path, class:"btn home-banner-btn" %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar sticky-top">
  <div>
    <%= link_to "KP", root_path, class: "name" %>
  </div>

  <div class="d-inline-flex justify-content-evenly">
    <%= link_to "Home", root_path, class: "nav-link" %>
    <%= link_to "Projects", projects_path, class: "nav-link" %>
    <%= link_to "About", about_path, class: "nav-link" %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KPenzes - Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <%= favicon_link_tag %>

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row justify-content-center">

    <div class="card about-card col-11 col-lg-4">

        <div class="details-flex">
          <div class="about-header">
            <p>Le Wagon, Montreal</p>
          </div>
          <div class="label">
            <p>Certification</p>
          </div>
        </div>
        <p>April 2023 - June 2023</p>
          <p>Full-stack web development 9-week intensive bootcamp</p>

        <div class="details-flex">
          <div class="about-header">
            <p>Concordia University</p>
          </div>
          <div class="label">
            <p>Bachelor's degree</p>
          </div>
        </div>
        <p>2014 - 2018</p>
        <p>History (major), Canadian-Irish Studies (minor)</p>

        <div class="about-section">
          <div class="about-header">
            <p>Languages & Skills</p>
          </div>
          <ul>
            <li>Ruby / Ruby on Rails</li>
            <li>HTML / CSS / SCSS</li>
            <li>Javascript ES6 / Stimulus</li>
            <li>React.js</li>
            <li>Next.js </li>
            <li>Webpack JS</li>
            <li>Bootstrap</li>
            <li>Postgresql</li>
            <li>Git</li>
          </ul>

        </div>

    </div>

    <div class="col-11 col-lg-6">

      <div class ="card about-card">

    <div class="about-details">
      <h1>Hi, my name is Kirstin!</h1>
      <p>A web developer from Montreal.</p>
      <p>Currently seeking freelancing opportunities - let's talk!</p>

      <div class="d-flex justify-content-center mb-2">
        <%= link_to "LinkedIn", "https://www.linkedin.com/in/kirstin-penzes/", class:"btn" %>
        <%= link_to "GitHub", "https://github.com/KPenzes", class:"btn" %>
      </div>
    </div>
        <p>
          Having experience in Customer Success for a decade, my work is
          shaped by a deep understanding of client needs and perspective.
          <br>
          <br>
          I believe that the foundation of Customer Success lies with the
        product, website or application itself. By expanding my skills to
        include web development, I've deepened my understanding of the
        customer experience.
          <br>
          <br>
          I'm pursuing a career that's driven by my passion for continuous learning and strengthens my skills and expertise.
        </p>
      </div>

      <div class ="card about-card contact">
        <p>
          <strong>Are you looking to get your project off the ground? Let's talk!</strong>
          <br>
          <br>
          You can contact me via <strong><a href="https://www.linkedin.com/in/kirstin-penzes/" target="_blank" style="color:#87CABA" >LinkedIn</a></strong>.
        </p>
      </div>
      <div class ="card about-card">
        <%= link_to "All projects", projects_path, class:"btn" %>
      </div>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<%= render "layouts/home_banner" %>

<div class="container">
  <div class="row justify-content-center">

    <div class="card card-home col-11 col-lg-5">
        <div class="card-home-infos">
          <h2>Currently working on </h2>

          <div class="details-flex">
            <div class="card-title">
              <p><%= @project.name %></p>
            </div>
            <div class="label">
              <p><%= @project.label %> project</p>
            </div>
          </div>

            <p><%= @project.description %></p>
        </div>

        <%= link_to "All projects", projects_path, class:"btn card-button" %>
    </div>


    <div class="card card-home col-11 col-lg-5">
      <div class="card-home-infos">
        <h2>Currently learning </h2>
          <div class="details-flex">
            <div class="card-title">
              <p>React.js & Next.js</p>
            </div>
            <div class="label">
              <p>Online course</p>
            </div>
          </div>
            <p>I'm focusing on expanding and improving my front-end skills, starting with learning React and the Next.js framework to use with my next project.</p>

            <%= link_to "About me", about_path, class:"btn card-button" %>

      </div>
    </div>

  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <% @projects.each do |project| %>
        <div class="card card-home project-card col-11 col-lg-5">
            <div class="project-details">

              <div class="details-flex">
                <div class="card-title">
                  <p><%= project.name %></p>
                </div>
                <div class="label">
                  <p><%= project.label %> project</p>
                </div>
              </div>

              <div class="details-flex">
                <p><%= project.tagline %></p>
                <% if project.end_date.present? %>
                  <p><%= project.start_date.to_formatted_s(:short) %> - <%= project.end_date.to_formatted_s(:short) %></p>
                <% else %>
                  <p><%= project.start_date.to_formatted_s(:short) %> - present </p>
                <% end %>
              </div>
            </div>

            <p><%= project.description %></p>
          <%= link_to "View details", project_path(project), class:"btn card-button" %>
        </div>
    <% end %>
  </div>

</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="card card-height col-11 col-lg-6">
      <div class="project-details">
        <div class="details-flex">
          <h1><%= @project.name %></h1>
          <div class="label">
            <p><%= @project.label %> project</p>
          </div>
        </div>
        <div class="details-flex">
          <p><%= @project.tagline %></p>
          <% if @project.end_date.present? %>
            <p><%= @project.start_date.to_formatted_s(:short) %> - <%= @project.end_date.to_formatted_s(:short) %></p>
          <% else %>
            <p><%= @project.start_date.to_formatted_s(:short) %> - present </p>
          <% end %>
        </div>
      </div>
        <h5>Description</h5>
          <p><%= @project.description %></p>
        <div class="d-flex justify-content-center mb-10">
          <%= link_to @project.name, @project.project_url, class:"btn small-btn mb-2" %>
          <%= link_to "GitHub", @project.github_url, class:"btn small-btn mb-2" %>
        </div>

      <% unless @project.features.empty? %>
        <div class="project-details mt-15">
          <h5>Features</h5>
        </div>
        <ul>
          <% @project.features.each do |feature| %>
            <li><%= feature %></li>
          <% end %>
        </ul>
      <% end %>

        <div class="project-details mt-15">
          <h5>Languages</h5>
        </div>
        <ul>
          <% @project.language.each do |language| %>
            <li><%= language %></li>
          <% end %>
        </ul>
    </div>

    <% unless @project.photos.empty? %>
      <div class="card card-align col-11 col-lg-4">
        <% @project.photos.each do |photo| %>
          <%= cl_image_tag photo.key, alt:"Homepage of project", class:"screenshot" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>